//! Integration tests for Icarus SDK

use icarus::prelude::*;
use serde_json::json;

#[icarus_server(name = "test-server", version = "1.0.0")]
pub struct TestServer;

#[icarus_tools]
impl TestServer {
    pub fn new() -> Self {
        Self
    }
    
    #[icarus_tool(name = "hello")]
    pub async fn hello(&self) -> ToolResult {
        Ok(json!({ "message": "Hello from test server!" }))
    }
}

#[test]
fn test_macro_compilation() {
    // This test mainly verifies that the macros expand correctly
    // and produce compilable code. The fact that we can create
    // a server instance proves the macros work.
    let _server = TestServer::new();
    
    // These methods are generated by the macros
    // We can't call them outside a canister, but their existence
    // proves the macro expansion worked
    
    // The compilation of this test is the actual test
}