//! Authentication tool wrappers module
//!
//! This module provides the namespace for authentication-related MCP tools.
//! The actual tool functions are auto-generated by the icarus_module macro
//! when used in canister implementations.
//!
//! # Usage
//! ```ignore
//! // This example requires the icarus crate and procedural macros not available in doc tests
//! // In your canister's lib.rs
//! use icarus::prelude::*;
//!
//! #[icarus_module]
//! mod tools {
//!     // Your tool functions here
//!     // The macro will automatically generate auth management functions:
//!     // - add_authorized_user
//!     // - remove_authorized_user
//!     // - update_user_role
//!     // - get_current_user
//! }
//! ```

// This module is only available when the canister feature is enabled
#[cfg(feature = "canister")]
pub use crate::auth::*;