# Clippy configuration for Icarus SDK
# This file enforces code quality standards and prevents common anti-patterns

# Prevent unwrap in production code
disallowed-methods = [
    { path = "std::option::Option::unwrap", reason = "use proper error handling with ? operator or expect() with descriptive message" },
    { path = "std::result::Result::unwrap", reason = "use ? operator or expect() with descriptive message" },
]

# Function complexity limits
too-many-arguments-threshold = 5
type-complexity-threshold = 100
cognitive-complexity-threshold = 30