[package]
name = "icarus"
version = "0.6.0"
authors = ["Icarus SDK Contributors"]
edition = "2021"
license-file = "LICENSE"
repository = "https://github.com/galenoshea/icarus-sdk"
documentation = "https://docs.rs/icarus"
homepage = "https://github.com/galenoshea/icarus-sdk"
readme = "README.md"
description = "Build MCP (Model Context Protocol) servers that run as Internet Computer canisters"
keywords = ["icp", "internet-computer", "mcp", "ai", "canister"]
categories = ["development-tools", "web-programming", "wasm"]

[features]
default = ["canister"]
canister = ["dep:icarus-canister", "dep:icarus-derive", "dep:icarus-core"]
core = ["dep:icarus-core"]

[dependencies]
icarus-core = { version = "0.6.0", path = "crates/icarus-core", optional = true }
icarus-derive = { version = "0.6.0", path = "crates/icarus-derive", optional = true }
icarus-canister = { version = "0.6.0", path = "crates/icarus-canister", optional = true }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
candid = "0.10"

# Known Issues:
# - paste 1.0.15 (RUSTSEC-2024-0436): Unmaintained transitive dependency from rmcp and candid.
#   This is not a security vulnerability, just an unmaintained crate warning.
#   Waiting for upstream crates to update their dependencies.

[workspace]
members = [
    "crates/icarus-core",
    "crates/icarus-derive",
    "crates/icarus-canister",
    "cli",
]
resolver = "2"

[[test]]
name = "unit_session"
path = "tests/unit/test_session.rs"

[[test]]
name = "unit_tools"
path = "tests/unit/test_tools.rs"

[[test]]
name = "integration_sdk_workflow"
path = "tests/integration/test_sdk_workflow.rs"

[workspace.package]
version = "0.6.0"
authors = ["Icarus SDK Contributors"]
edition = "2021"
license-file = "LICENSE"
repository = "https://github.com/galenoshea/icarus-sdk"

[workspace.dependencies]
# External dependencies  
rmcp = "0.6"
# Override problematic time dependencies to disable wasm features
chrono = { version = "0.4", default-features = false, features = [
    "std",
    "serde",
] }
web-time = { version = "1.1", default-features = false }
ic-cdk = "0.18"
ic-cdk-macros = "0.18"
ic-cdk-timers = "0.12"
ic-stable-structures = "0.7"
ic-management-canister-types = "0.3"
candid = "0.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
tokio = { version = "1", features = ["full"] }
async-trait = "0.1"
tracing = "0.1"
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
linkme = "0.3"

# Internal dependencies
icarus-core = { path = "crates/icarus-core", version = "0.6.0" }
icarus-derive = { path = "crates/icarus-derive", version = "0.6.0" }
icarus-canister = { path = "crates/icarus-canister", version = "0.6.0" }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true

[profile.dev]
opt-level = 0
debug = true
