# Cargo Release Configuration
# This file configures cargo-release to automatically update version strings
# across all project files from a single source of truth

# Don't automatically push (we'll do it manually after verification)
push = false
publish = false

# Commit settings
pre-release-commit-message = "chore: release version {{version}}"
tag-message = "Release version {{version}}"
tag-name = "v{{version}}"

# Sign commits and tags if GPG is configured
sign-commit = false
sign-tag = false

# Replacements for version strings in documentation
[[pre-release-replacements]]
file = "README.md"
search = 'icarus = "[0-9]+\.[0-9]+\.[0-9]+"'
replace = 'icarus = "{{version}}"'
min = 1

[[pre-release-replacements]]
file = "README.md"
search = 'icarus-canister = "[0-9]+\.[0-9]+\.[0-9]+"'
replace = 'icarus-canister = "{{version}}"'
min = 1

[[pre-release-replacements]]
file = "README.md"
search = 'cargo install icarus-cli@[0-9]+\.[0-9]+\.[0-9]+'
replace = 'cargo install icarus-cli@{{version}}'
min = 0

[[pre-release-replacements]]
file = "README.md"
search = 'icarus-core = "[0-9]+\.[0-9]+\.[0-9]+"'
replace = 'icarus-core = "{{version}}"'
min = 0

[[pre-release-replacements]]
file = "README.md"
search = 'icarus-derive = "[0-9]+\.[0-9]+\.[0-9]+"'
replace = 'icarus-derive = "{{version}}"'
min = 0

# Update version notices in README if present
[[pre-release-replacements]]
file = "README.md"
search = 'Version [0-9]+\.[0-9]+\.[0-9]+\+'
replace = 'Version {{version}}+'
min = 0

# Workspace configuration
[workspace]
# Update all workspace members together
members = ["crates/icarus-core", "crates/icarus-derive", "crates/icarus-canister", "cli"]