# Configuration for cargo-release
# This ensures all workspace crates are versioned and released together

# All workspace members share the same version
shared-version = true

# Sign commits and tags
sign-commit = false
sign-tag = false

# Push changes to remote
push = true
push-remote = "origin"

# Create and push tags
tag = true
tag-prefix = ""  # Empty to prevent double 'v' when using 'cargo release v0.x.x'
tag-message = "Release version {{version}}"

# Commit message format
pre-release-commit-message = "Release version {{version}}"

# Don't publish to crates.io automatically (GitHub Actions will handle this)
publish = false

# Update dependent crate versions
dependent-version = "upgrade"

# Verification steps before release
verify = true

# Consolidate commits into a single commit
consolidate-commits = true

# Pre-release replacements to update version references
[[pre-release-replacements]]
file = "README.md"
search = 'icarus = "[0-9]+\.[0-9]+"'
replace = 'icarus = "{{version}}"'

[[pre-release-replacements]]
file = "README.md"
search = 'icarus-canister = "[0-9]+\.[0-9]+"'
replace = 'icarus-canister = "{{version}}"'