[package]
name = "basic-memory-example"
version = "0.1.0"
edition = "2021"

[dependencies]
icarus = { path = "../.." }
ic-cdk = "0.16"
candid = "0.10"
serde = { version = "1.0", features = ["derive"] }

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = "z"
lto = true