[package]
name = "http-fetcher"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
icarus = { path = "../../", features = ["canister"] }
candid = "0.10"
ic-cdk = "0.16"
ic-cdk-macros = "0.16"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"